version: '3'
services:
  ethereum:
    ports:
      - 8545:8545
      - 30303:30303
    image: ethereum/client-go
    command: --http --http.addr 0.0.0.0 --syncmode light
    volumes:
      - type: bind
        source: ./ethereum_data
        target: /root
    networks:
      - containers

networks:
  containers:
